# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94b109526e60e4bb67ded682aae4673a"
name = "wishlist-inspire"
handle = "wishlist-inspire-125"
application_url = "https://symptoms-newbie-fired-quote.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "makeinfo-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://symptoms-newbie-fired-quote.trycloudflare.com/auth/callback",
  "https://symptoms-newbie-fired-quote.trycloudflare.com/auth/shopify/callback",
  "https://symptoms-newbie-fired-quote.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
